"""Add handout_image and handover_image fields to sessions

Revision ID: 0003_add_session_images
Revises: 0001_init_users
Create Date: 2025-10-02 15:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_add_session_images'
down_revision: Union[str, None] = '0002_sessions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('handout_image', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('handover_image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'handover_image')
    op.drop_column('sessions', 'handout_image')
    # ### end Alembic commands ###
